# Generated by Django 5.1.1 on 2024-09-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CONNETADO', 'Conectado'), ('DESCONECTADO', 'Desconectado')], default='DESCONECTADO', max_length=15)),
            ],
        ),
    ]
