# Generated by Django 5.1.1 on 2024-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('CONECTADO', 'Conectado'), ('DESCONECTADO', 'Desconectado')], default='DESCONECTADO', max_length=15),
        ),
    ]
