# Generated by Django 5.1.1 on 2024-09-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_veiculo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
